--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: taccount; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.taccount (
    account_status character varying(3) NOT NULL,
    account_type character varying(3) NOT NULL,
    initial_amount numeric(19,11) NOT NULL,
    account_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    CONSTRAINT taccount_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACT'::character varying, 'INA'::character varying, 'BLK'::character varying, 'DEL'::character varying])::text[]))),
    CONSTRAINT taccount_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['SAV'::character varying, 'CHK'::character varying])::text[])))
);


ALTER TABLE public.taccount OWNER TO postgres;

--
-- Name: taccount_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.taccount ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taccount_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ttransaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ttransaction (
    amount numeric(19,11) NOT NULL,
    balance numeric(19,11) NOT NULL,
    transaction_type character varying(3) NOT NULL,
    account_id bigint NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    transaction_id bigint NOT NULL,
    CONSTRAINT ttransaction_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['DEB'::character varying, 'CRE'::character varying])::text[])))
);


ALTER TABLE public.ttransaction OWNER TO postgres;

--
-- Name: ttransaction_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ttransaction ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ttransaction_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: taccount; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.taccount (account_status, account_type, initial_amount, account_id, customer_id) FROM stdin;
ACT	SAV	100.00000000000	2	2
ACT	SAV	100.00000000000	3	3
DEL	CHK	10.00000000000	1	1
\.


--
-- Data for Name: ttransaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ttransaction (amount, balance, transaction_type, account_id, transaction_date, transaction_id) FROM stdin;
50.00000000000	50.00000000000	CRE	1	2024-08-24 23:36:04.072	1
100.00000000000	100.00000000000	CRE	2	2024-08-24 23:36:40.821	2
100.00000000000	100.00000000000	CRE	3	2024-08-24 23:36:54.191	3
10.00000000000	60.00000000000	CRE	1	2024-08-24 23:37:52.451	4
20.00000000000	80.00000000000	CRE	1	2024-08-24 23:38:09.336	5
-15.00000000000	65.00000000000	DEB	1	2024-08-24 23:38:17.954	6
-5.00000000000	95.00000000000	DEB	2	2024-08-24 23:38:28.67	7
\.


--
-- Name: taccount_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.taccount_account_id_seq', 3, true);


--
-- Name: ttransaction_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ttransaction_transaction_id_seq', 7, true);


--
-- Name: taccount taccount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.taccount
    ADD CONSTRAINT taccount_pkey PRIMARY KEY (account_id);


--
-- Name: ttransaction ttransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ttransaction
    ADD CONSTRAINT ttransaction_pkey PRIMARY KEY (transaction_id);


--
-- Name: ttransaction fkiqi5g3mnbmy97o2ffrf7bp8du; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ttransaction
    ADD CONSTRAINT fkiqi5g3mnbmy97o2ffrf7bp8du FOREIGN KEY (account_id) REFERENCES public.taccount(account_id);


--
-- PostgreSQL database dump complete
--

