server:
  port: ${PORT:9090}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          username: ${GIT_USER_NAME}
          password: ${GIT_USER_PASSWORD}
          clone-on-start: true
          default-label: main
          search-paths: devsu-config/config-server-files
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:9091/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"