server:
  port: ${PORT:9090}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI:https://github.com/paigvimo/devsu-001.git}
          username: ${GIT_USER_NAME:paigvimo}
          password: ${GIT_USER_PASSWORD}
          clone-on-start: true
          default-label: main
          search-paths: devsu-config/config-server-files
management:
  endpoints:
    web:
      exposure:
        include: "*"